#!/usr/bin/env python3
"""Regression tests for production DOCX export formatting pipeline."""

import os
import re
import shutil
import sys
import zipfile
from pathlib import Path

import pytest


PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENGINE_ROOT = PROJECT_ROOT / "engine"
sys.path.insert(0, str(ENGINE_ROOT))

from utils.docx_export_pipeline import normalize_docx_language, preprocess_markdown_for_docx, select_reference_template
from utils.export_professional import export_docx


ZH_SAMPLE = """---
title: 人工智能背景下就业观念变迁及其社会影响研究
language: zh
date: 2026-05-02
---

人工智能背景下就业观念变迁及其社会影响研究

# Table of Contents

## 1. 摘要

**Research Problem and Approach:** 本文梳理人工智能背景下就业观念变迁。

**Methodology and Findings:** 文献显示就业评价标准发生变化。

**Key Contributions:** 提供社会影响分析框架。

**Implications:** 为教育与劳动政策提供参考。

**Keywords:** 人工智能；就业观念；社会影响

\\newpage

# · 1. Introduction

正文段落。

## 1.1 Theoretical Framework

表 9 错误旧编号

| 维度 | 影响路径 |
| --- | --- |
| 技能 | 岗位重组 |

# 5. References

Https://doi.org/10.1000/example
"""


ZH_DRONE_SAMPLE = """---
title: 基于无人机遥感与深度学习的农作物病虫害识别研究
language: zh
date: 2026-05-02
---

基于无人机遥感与深度学习的农作物病虫害识别研究

Title

Document Type

Generated by

Disclaimer

Table of Contents

Right-click and update field to refresh the table of contents.

# 1. 摘要

本文研究无人机遥感与深度学习在农作物病虫害识别中的应用。

**关键词：** 无人机遥感；深度学习；病虫害识别

\\newpage

# · 1. 引言

无人机遥感为农田病虫害监测提供了高时空分辨率数据。

# · 2. 正文

表1：不同病害识别技术对比

| 技术类型 | 代表算法 | 应用优势 | 局限性 |
| --- | --- | --- | --- |
| 传统机器学习 | SVM | 可解释性较强 | 特征依赖人工设计 |
| 深度学习 | CNN | 自动提取特征 | 需要较多标注数据 |

Table 2. Table 2 识别性能比较

| Performance | Accuracy |
| --- | --- |
| CNN | 92% |

## 2.1 方法论框架

方法包括影像采集、标注、模型训练与验证。

## 2.2 分析与结果

结果表明深度学习模型具有较高识别精度。

## 2.3 讨论

模型泛化能力仍需增强。

# · 3. 结论

该方法可提升病虫害识别效率{(Wang et al., 2023)}{(萧 男 et al., 2025)}。

# 4. References

Wang et al. (2023). Example.
"""


EN_SAMPLE = """---
title: Microstructural Evolution and Performance Control of Metallic Materials in Additive Manufacturing
language: en
date: 2026-05-02
---

## Abstract

**Research Problem and Approach:** This draft reviews metallic materials in additive manufacturing.

**Keywords:** Additive Manufacturing; Laser Powder Bed Fusion

newpage

# 1. Introduction

Cooling rates exceeding $10^6$ K/s influence thermal gradients ($G$), growth velocity ($R$), and the resulting $G/R$ ratio.

Table 8. Old duplicate number

| Microstructural Outcome | Applicable Material Classes | Representative Study | Documented impacts |
| --- | --- | --- | --- |
| Columnar grains | Nickel alloys and steels | Example et al. | Strength anisotropy |

## 1.1 Background

Text.

# References

https://doi.org/10.1000/example
"""


def test_preprocess_chinese_localizes_and_cleans_docx_markdown():
    cleaned, stats = preprocess_markdown_for_docx(ZH_SAMPLE, "zh")

    assert stats.language == "zh"
    assert stats.tables_processed == 1
    assert stats.captions_generated == 1
    assert "Table of Contents" not in cleaned
    assert "人工智能背景下就业观念变迁及其社会影响研究" not in cleaned
    assert "Research Problem and Approach" not in cleaned
    assert "研究问题与研究方法" in cleaned
    assert "关键词：" in cleaned
    assert "```{=openxml}" in cleaned
    assert "ewpage" not in cleaned
    assert "\\newpage" not in cleaned
    assert "Https://doi.org" not in cleaned
    assert "https://doi.org/10.1000/example" in cleaned
    assert "表 1" in cleaned
    assert "# 摘要" in cleaned
    assert "# 1. 引言" in cleaned
    assert "# · 1. 引言" not in cleaned
    assert "# 参考文献" in cleaned


def test_preprocess_english_preserves_labels_and_math_readability():
    cleaned, stats = preprocess_markdown_for_docx(EN_SAMPLE, "en")

    assert stats.language == "en"
    assert "Table 1." in cleaned
    assert "10⁶ K/s" in cleaned
    assert "G/R ratio" in cleaned
    assert "Research Problem and Approach" in cleaned
    assert "```{=openxml}" in cleaned
    assert "newpage" not in cleaned


def test_preprocess_detects_malformed_caption_pipe_table():
    malformed = """---
title: Bad table
language: zh
---

Table 1. Table 1 | 技术类型 | 代表算法 |
| 深度学习 | CNN |
"""
    with pytest.raises(ValueError, match="Malformed markdown table"):
        preprocess_markdown_for_docx(malformed, "zh")


def test_chinese_detection_tolerates_many_english_references():
    text = (
        "本文讨论无人机遥感与深度学习在农作物病虫害识别中的应用，并分析模型泛化能力与田间部署价值。" * 20
        + "\n".join(f"https://doi.org/10.1000/example{i} Wang et al. reference text" for i in range(30))
    )
    assert normalize_docx_language(None, text) == "zh"


def test_preprocess_chinese_drone_sample_removes_regression_residue():
    cleaned, stats = preprocess_markdown_for_docx(ZH_DRONE_SAMPLE, "zh")

    assert stats.tables_processed == 2
    assert stats.captions_generated == 2

    forbidden = [
        "基于无人机遥感与深度学习的农作物病虫害识别研究",
        "Table of Contents",
        "Right-click and update field",
        "\nTitle\n",
        "Document Type",
        "Generated by",
        "Disclaimer",
        "Table 1. Table 1",
        "Table 2. Table 2",
        "# 1. 摘要",
        "# · 1. 引言",
        "{(",
        ")}",
        "\\newpage",
        "ewpage",
    ]
    for marker in forbidden:
        assert marker not in cleaned

    required = [
        "# 摘要",
        "关键词",
        "# 1. 引言",
        "# 2. 正文",
        "# 3. 结论",
        "# 参考文献",
        "表 1  不同病害识别技术对比",
        "表 2  识别性能比较",
        "| 技术类型 | 代表算法 | 应用优势 | 局限性 |",
    ]
    for marker in required:
        assert marker in cleaned


def test_preprocess_converts_table_caption_headings_to_plain_captions():
    sample = """---
title: 表题标题测试
language: zh
---

# 1. 正文

### 1.3.1. 表1 技术路线比较
| 维度 | 内容 |
| --- | --- |
| 路线 | 对比 |
"""

    cleaned, stats = preprocess_markdown_for_docx(sample, "zh")

    assert stats.markdown_tables_detected == 1
    assert stats.caption_headings_normalized == 1
    assert stats.captions_generated == 1
    assert "### 1.3.1. 表1" not in cleaned
    assert "表 1  技术路线比较\n\n| 维度 | 内容 |" in cleaned


def test_preprocess_english_table_caption_heading_to_plain_caption():
    sample = """---
title: Caption heading test
language: en
---

# 1. Body

### 1.2.1. Table 3 Evaluation results
| A | B |
| --- | --- |
| x | y |
"""

    cleaned, stats = preprocess_markdown_for_docx(sample, "en")

    assert stats.markdown_tables_detected == 1
    assert stats.caption_headings_normalized == 1
    assert "### 1.2.1. Table 3" not in cleaned
    assert "Table 1. Evaluation results\n\n| A | B |" in cleaned


@pytest.mark.parametrize(
    "bad_text",
    [
        "thermal gradients (), growth velocity R",
        "cooling rates exceeding  K/s",
        "the resulting  ratio",
    ],
)
def test_preprocess_blocks_empty_math_variables(bad_text):
    with pytest.raises(ValueError):
        preprocess_markdown_for_docx(f"---\ntitle: t\n---\n\n{bad_text}", "en")


def test_preprocess_allows_low_risk_empty_parentheses():
    cleaned, _stats = preprocess_markdown_for_docx("This section uses empty parentheses () as an editorial marker.", "en")
    assert "()" in cleaned


def test_reference_templates_exist():
    assert select_reference_template("zh").exists()
    assert select_reference_template("en").exists()


def _style_xml(path: Path, style_id: str) -> str:
    with zipfile.ZipFile(path) as zf:
        xml = zf.read("word/styles.xml").decode("utf-8")
    match = re.search(
        rf'<w:style\b(?=[^>]*w:styleId="{re.escape(style_id)}")[\s\S]*?</w:style>',
        xml,
    )
    assert match, f"Missing style {style_id} in {path}"
    return match.group(0)


def test_chinese_reference_template_is_readable_style_source():
    template = select_reference_template("zh")
    with zipfile.ZipFile(template) as zf:
        styles_xml = zf.read("word/styles.xml").decode("utf-8")

    normal = _style_xml(template, "Normal")
    heading1 = _style_xml(template, "Heading1")
    heading2 = _style_xml(template, "Heading2")
    heading3 = _style_xml(template, "Heading3")
    caption = _style_xml(template, "Caption")

    assert "SimSun" not in styles_xml
    assert 'w:eastAsia="Noto Serif CJK SC"' in normal
    assert 'w:ascii="Times New Roman"' in normal
    assert 'w:sz w:val="24"' in normal
    assert 'w:line="360"' in normal
    assert 'w:after="60"' in normal
    assert 'w:firstLine="420"' in normal
    assert 'w:jc w:val="left"' in normal

    assert 'w:sz w:val="32"' in heading1
    assert 'w:before="240"' in heading1
    assert 'w:after="120"' in heading1
    assert 'w:firstLine="0"' in heading1
    assert 'w:sz w:val="28"' in heading2
    assert 'w:before="200"' in heading2
    assert 'w:after="80"' in heading2
    assert 'w:sz w:val="24"' in heading3
    assert 'w:before="120"' in heading3
    assert 'w:after="60"' in heading3
    assert 'w:jc w:val="left"' in caption


def test_english_reference_template_uses_left_aligned_body_and_headings():
    template = select_reference_template("en")
    normal = _style_xml(template, "Normal")
    heading1 = _style_xml(template, "Heading1")

    assert 'w:sz w:val="22"' in normal
    assert 'w:jc w:val="left"' in normal
    assert 'w:jc w:val="left"' in heading1


def test_export_docx_requires_pandoc_and_does_not_call_basic(monkeypatch, tmp_path):
    input_md = tmp_path / "draft.md"
    input_md.write_text(EN_SAMPLE, encoding="utf-8")

    import utils.export_professional as export_module

    original_which = shutil.which
    monkeypatch.setattr(shutil, "which", lambda cmd: None if cmd == "pandoc" else original_which(cmd))
    monkeypatch.setattr(
        export_module,
        "export_docx_basic",
        lambda *_args, **_kwargs: (_ for _ in ()).throw(AssertionError("basic fallback called")),
    )

    assert export_docx(input_md, tmp_path / "out.docx") is False


def test_export_docx_requires_reference_template(monkeypatch, tmp_path):
    input_md = tmp_path / "draft.md"
    input_md.write_text(EN_SAMPLE, encoding="utf-8")

    import utils.export_professional as export_module

    monkeypatch.setattr(shutil, "which", lambda cmd: "/usr/bin/pandoc" if cmd == "pandoc" else None)
    monkeypatch.setattr(export_module, "select_reference_template", lambda _lang: tmp_path / "missing.docx")

    assert export_docx(input_md, tmp_path / "out.docx") is False


def _docx_xml(path: Path, name: str = "word/document.xml") -> str:
    with zipfile.ZipFile(path) as zf:
        return zf.read(name).decode("utf-8")


def _all_docx_xml(path: Path) -> str:
    with zipfile.ZipFile(path) as zf:
        return "\n".join(
            zf.read(name).decode("utf-8", errors="ignore")
            for name in zf.namelist()
            if name.startswith("word/") and name.endswith(".xml")
        )


def test_docx_post_processor_creates_word_structures(tmp_path):
    docx = pytest.importorskip("docx")
    from utils.docx_post_processor import insert_academic_structure

    output = tmp_path / "sample.docx"
    doc = docx.Document()
    doc.add_heading("摘要", level=1)
    doc.add_paragraph("关键词：人工智能；就业观念")
    doc.add_heading("1. 引言", level=1)
    doc.add_paragraph("正文段落。")
    doc.add_paragraph("表 9  旧表题")
    table = doc.add_table(rows=2, cols=2)
    table.cell(0, 0).text = "维度"
    table.cell(0, 1).text = "影响"
    table.cell(1, 0).text = "技能"
    table.cell(1, 1).text = "岗位"
    doc.add_heading("参考文献", level=1)
    doc.add_paragraph("作者. (2025). 题名. https://doi.org/10.1000/example")
    doc.save(output)

    stats = insert_academic_structure(
        output,
        options={"language": "zh", "title": "人工智能背景下就业观念变迁及其社会影响研究"},
    )

    assert stats["tables_processed"] == 1
    assert stats["captions_generated"] == 1
    assert stats["docx_tables_detected"] == 1

    xml = _docx_xml(output)
    assert "Right-click and update field" not in xml
    assert "TOC \\o &quot;1-3&quot;" not in xml
    assert 'w:type="page"' in xml
    assert "tblHeader" in xml
    assert "cantSplit" in xml
    assert "tblW" in xml
    assert "PAGE" not in _all_docx_xml(output)

    processed = docx.Document(output)
    texts = "\n".join(p.text for p in processed.paragraphs)
    assert "目录" not in texts
    assert "摘要" in texts
    assert "关键词" in texts
    assert "参考文献" in texts
    assert "Table of Contents" not in texts
    assert "Document Type" not in texts
    assert "Generated by" not in texts
    assert "Disclaimer" not in texts
    assert "ewpage" not in texts


@pytest.mark.skipif(shutil.which("pandoc") is None, reason="Pandoc is not installed")
def test_export_docx_generates_real_docx_when_pandoc_available(tmp_path):
    docx = pytest.importorskip("docx")
    input_md = tmp_path / "draft.md"
    output = tmp_path / "draft.docx"
    input_md.write_text(EN_SAMPLE, encoding="utf-8")

    assert export_docx(input_md, output)

    document = docx.Document(output)
    texts = "\n".join(p.text for p in document.paragraphs)
    assert "Table of Contents" not in texts
    assert "Abstract" in texts
    assert "Keywords" in texts
    assert "References" in texts
    assert "newpage" not in texts
    assert len(document.tables) == 1


def test_docx_post_processor_does_not_create_empty_toc_or_page_numbers(tmp_path):
    docx = pytest.importorskip("docx")
    from utils.docx_post_processor import insert_academic_structure

    output = tmp_path / "no_toc.docx"
    doc = docx.Document()
    doc.add_heading("摘要", level=1)
    doc.add_paragraph("关键词：无人机遥感")
    doc.add_heading("1. 引言", level=1)
    doc.add_paragraph("正文。")
    doc.save(output)

    assert insert_academic_structure(output, options={"language": "zh", "title": "测试文档"})
    processed = docx.Document(output)
    texts = "\n".join(p.text for p in processed.paragraphs)
    assert "目录" not in texts
    assert "Table of Contents" not in texts
    assert "PAGE" not in _all_docx_xml(output)


def test_docx_post_processor_does_not_treat_sentence_as_caption(tmp_path):
    docx = pytest.importorskip("docx")
    from utils.docx_post_processor import insert_academic_structure

    output = tmp_path / "caption_sentence.docx"
    doc = docx.Document()
    doc.add_heading("1. Introduction", level=1)
    doc.add_paragraph("Table 1 shows that the model improves accuracy across settings.")
    table = doc.add_table(rows=2, cols=2)
    table.cell(0, 0).text = "A"
    table.cell(0, 1).text = "B"
    table.cell(1, 0).text = "x"
    table.cell(1, 1).text = "y"
    doc.save(output)

    stats = insert_academic_structure(output, options={"language": "en", "title": "Caption sentence"})
    processed = docx.Document(output)
    texts = "\n".join(p.text for p in processed.paragraphs)
    assert "Table 1 shows that the model improves accuracy across settings." in texts
    assert stats["captions_generated"] == 0


@pytest.mark.skipif(shutil.which("pandoc") is None, reason="Pandoc is not installed")
def test_docx_export_regression_chinese_drone_sample(tmp_path):
    docx = pytest.importorskip("docx")
    input_md = tmp_path / "drone.md"
    output = tmp_path / "drone.docx"
    input_md.write_text(ZH_DRONE_SAMPLE, encoding="utf-8")

    assert export_docx(input_md, output)

    document = docx.Document(output)
    texts = "\n".join(p.text for p in document.paragraphs)

    forbidden = [
        "Right-click and update field",
        "目录",
        "Table of Contents",
        "Title",
        "Document Type",
        "Disclaimer",
        "Table 1. Table 1",
        "| 技术类型 |",
        "| ---",
        "| Performance |",
        "ewpage",
        "\\newpage",
        "{(",
        ")}",
    ]
    for marker in forbidden:
        assert marker not in texts

    required = ["摘要", "关键词", "1. 引言", "2. 正文", "3. 结论", "参考文献"]
    for marker in required:
        assert marker in texts

    for para in document.paragraphs:
        style = para.style.name if para.style else ""
        if style.startswith("Heading") and para.text.strip():
            assert not para.text.strip().startswith(("·", "-", "*"))

    assert len(document.tables) > 0
    captions = [p.text.strip() for p in document.paragraphs if p.text.strip().startswith(("表 ", "Table "))]
    assert captions
    assert all(not caption.startswith("Table ") for caption in captions)
    assert len(captions) == len(set(captions))
    numbers = [caption.split()[1] for caption in captions if caption.startswith("表 ") and len(caption.split()) > 1]
    assert len(numbers) == len(set(numbers))


def test_docx_post_processor_rejects_lost_markdown_tables(tmp_path):
    docx = pytest.importorskip("docx")
    from utils.docx_post_processor import insert_academic_structure

    output = tmp_path / "lost_table.docx"
    doc = docx.Document()
    doc.add_heading("1. 引言", level=1)
    doc.add_paragraph("表 1 | A | B |")
    doc.save(output)

    stats = insert_academic_structure(
        output,
        options={"language": "zh", "title": "表格失败测试", "markdown_tables_detected": 1},
    )

    assert stats == {}
